//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentVoucherDetail
    {
        public int Id { get; set; }
        public int AdjustmentVoucherId { get; set; }
        public int StationeryId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Reason { get; set; }
    
        public virtual AdjustmentVoucher AdjustmentVoucher { get; set; }
        public virtual Stationery Stationery { get; set; }
    }
}
