//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSIS.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Disbursement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disbursement()
        {
            this.RequisitionDetails = new HashSet<RequisitionDetail>();
        }

        public int Id { get; set; }
        public int DeliveredEmployeeId { get; set; }
        public Nullable<int> ReceivedEmployeeId { get; set; }
        public bool AdHoc { get; set; }
        public Nullable<System.DateTime> DeliveryDateTime { get; set; }
        public string CollectionPoint { get; set; }
        public byte[] Signature { get; set; }
        public bool OnRoute { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
    }
}
