//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierTender
    {
        public int Id { get; set; }
        public int StationeryId { get; set; }
        public int Rank { get; set; }
        public int Year { get; set; }
        public int SupplierId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Stationery Stationery { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
